export const tags = [
  { label: "Anime", value: "anime" },
  { label: "Manga", value: "manga" },
  { label: "Games", value: "games" },
  { label: "Movies", value: "movies" },
  { label: "Music", value: "music" },
  { label: "TV", value: "tv" },
  { label: "Books", value: "books" },
  { label: "Art", value: "art" },
  { label: "Science", value: "science" },
  { label: "Technology", value: "technology" },
  { label: "History", value: "history" },
  { label: "Travel", value: "travel" },
  { label: "Food", value: "food" },
  { label: "Fashion", value: "fashion" },
  { label: "Design", value: "design" },
];
